### ISSUE TITLE
Need documentation for setting up the Windows build

### ISSUE THREAD

**Issue by stuarteberg** [ilastik/ilastik-build-conda#16]
Getting the Windows build environment set up on a machine is non-trivial, and we should document the process for doing so.

Side note: Right now the windows build is in a totally different branch (`toolset-config`).  That won't change any time soon, because we're waiting on some changes in conda-build.  But we should still document the current setup.  I think the right place to do so is in the toolset-config branch, possibly in README.md or maybe in a separate branch.

cc @ilastikdev @ukoethe

**Comment by k-dominik** [comment]
windows build is now more or less the same as linux and mac. We're using `ilastik-publish-packages` now everywhere.
