### ISSUE TITLE
Remove uses of __conda_version__.txt

### ISSUE THREAD

**Issue by stuarteberg** [ilastik/ilastik-build-conda#19]
conda-build is now issuing a warning:

```
Deprecation warning: support for __conda_version__ will be removed in Conda build 2.0.Try Jinja templates instead: http://conda.pydata.org/docs/building/environment-vars.html#git-environment-variables
```

FWIW, I agree with their decision to deprecate `__conda_version__`.  But we'll need to fix it before we upgrade to conda 2.0.

**Comment by k-dominik** [comment]
don't see any of those around - closing.
