### ISSUE TITLE
Sphinx for documentation is missing in environment

### ISSUE THREAD

**Issue by shaker6691** [ilastik/ilastik-build-conda#23]
It would be nice to have sphinx preinstalled. This is sufficient for compiling the documentation.

**Comment by stuarteberg** [comment]
A not-too-old version of the compiled developer documentation for the primary repos can be found in the following places.

http://ilastik.github.io/ilastik
http://ilastik.github.io/lazyflow
http://ilastik.github.io/volumina

To install sphinx into the Linux binary environment, use conda's `-p` option:

```
conda install -p /path/to/ilastik-1.2.0rc10-Linux sphinx
```

**Comment by shaker6691** [comment]
Thanks
