### ISSUE TITLE
ilastik-versions needs to be updated on the ilastik conda channel

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik-build-conda#29]
Disclaimer: I have only tested this with the `...-no-solvers` version of ilastik.

While `mamutexport` is specified in [ilastik-versions/meta.yaml](https://github.com/ilastik/ilastik-build-conda/blob/master/ilastik-versions/meta.yaml#L50) it isn't installed. Also a bunch of other packages doesn't seem to come with the right versions (e.g. jpeg). I think the package is just outdated on the ilastik conda channel.

This is related to https://github.com/ilastik/ilastik/issues/1480

**Comment by stuarteberg** [comment]
The problem was that I didn't upload the latest `ilastik-everything-no-solvers` package. (It isn't needed for the release binary, but it is needed for CI, as you just pointed out.)  Anyway, it's up-to-date now.

**Comment by k-dominik** [comment]
thanks a lot Stuart. Works like a charm. This also closes https://github.com/ilastik/ilastik/issues/1480
