### ISSUE TITLE
nifty-with-gurobi not found in ilastik-forge or conda-forge

### ISSUE THREAD

**Issue by clbarnes** [ilastik/ilastik-build-conda#63]
```
> lsb_release -a

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

> conda --version

conda 4.6.11

> python --version

Python 3.7.3

> conda install -c ilastik-forge -c conda-forge ilastik-dependencies-no-solvers

# lots of logging - tl;dr successful

> conda install nifty-with-gurobi -c ilastik-forge -c conda-forge

WARNING: The conda.compat module is deprecated and will be removed in a future release.
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - nifty-with-gurobi

Current channels:

  - https://conda.anaconda.org/ilastik-forge/linux-64
  - https://conda.anaconda.org/ilastik-forge/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by k-dominik** [comment]
Hi @clbarnes,

we don't build that recipe anymore. You don't need gurobi for the multicut to work. Is there any particular reason you want to use it?

It is still available in the "old-style" compiler stack with the label `cf201901` on ilastik-forge.

**Comment by clbarnes** [comment]
Thanks, that's good to know!

No reason I want to use it, I was just using the documented installation procedure. If that's no longer the right way to go about it, could the documentation be updated?

I wasn't able to install ilastik by downloading the binary from the website because the server's connection was terrible - my browser's file manager couldn't get it at all; wget only managed it after 4 hours and 7 dropouts.

**Comment by k-dominik** [comment]
oh wow, that binary downloads are so slow is horrible. I'll check if we can do anything about it.

are you referring to the installation instructions in this repo? Those are outdated, yes, sorry. I'll add a note and refer to the [contributing guidelines](https://github.com/ilastik/ilastik/blob/master/CONTRIBUTING.md) in our main repo until I have time to change that.

in short, you can now spin up an environment quickly, after cloning `ilastik-meta` and initializiing the submodules (and checking out master) by:

```
# assuming you are in .../ilastik-meta
python ilastik/scripts/devenv.py create -n idev -c ilastik-forge conda-forge defaults -p ilastik-dependencies-no-solvers
```
The commercial solvers are only needed for learning of tracking paramters in the tracking with learning workflow.

**Comment by clbarnes** [comment]
> oh wow, that binary downloads are so slow is horrible. I'll check if we can do anything about it.

Weird - I tried it from home (in an apartment on the Janelia campus) and it was absolutely fine. But trying it from both LAN and the guest WiFi in the Janelia main building had these issues. The issue may be at our end, although I'm stumped as to why!

> in short, you can now spin up an environment quickly, after cloning ilastik-meta and initializiing the submodules (and checking out master) by:

Great, thanks! And thanks for linking the contributing guidelines; should be able to get master working in my environment from there.
