### ISSUE TITLE
installation from conda broken

### ISSUE THREAD

**Issue by jburel** [ilastik/ilastik-build-conda#92]
We have been working on integration between IDR/OMERO and ilastik (popular during our training session). We install ilastik from Conda, use ilastik API and run the notebook in mybinder
I noticed last night that it is no longer possible to build the docker image using 
```
ilastik-dependencies-no-solvers==1.4
```
line from: https://github.com/ome/omero-guide-ilastik/blob/master/binder/environment.yml (for reference)

* successful build https://travis-ci.org/github/ome/omero-guide-ilastik/builds/707934313
* unsuccessful build with the same commit https://travis-ci.org/github/ome/omero-guide-ilastik/builds/708870755

Digging into the issue, the failure started to happen after then new conda packages e.g. ilastikrag were published few days ago

I have now updated the ``environment.yml`` (https://github.com/ome/omero-guide-ilastik/pull/20) so I can still use the part of the API

testing environment: linux

**Comment by jburel** [comment]
During my investigation I also noticed that ``scikit-image`` needs to be capped to 0.16.
Otherwise ``from skimage.external import tifffile`` will fail

**Comment by jburel** [comment]
I have managed to the successfully installed ``ilastiktools`` and ``ilastikrag`` using the version pushed today. This was not working yesterday evening

**Comment by jburel** [comment]
installing ``tiktorch`` does not work

**Comment by k-dominik** [comment]
Hi @jburel, sorry for not reacting to this at all, it slipped my attention completely. Sorry.

Do you still experience any problems?

**Comment by jburel** [comment]
HI @k-dominik I have opted to install package per package, it makes the installation a bit more complex but at least it works on every run. see https://github.com/ome/omero-guide-ilastik/blob/master/binder/environment.yml
We are using that to show how to analyse data in http://idr.openmicroscopy.org/ using ilastik

I have not tested the overarching package since the problem occurred

**Comment by jburel** [comment]
Hi @k-dominik
Few months ago, I opted to install package per package following the breakage.
Now that strategy is also broken
Now using the environment file mentioned in my previous comment, no longer works. 
```
ResolvePackageNotFound: 
  - ilastikrag==0.1.3.post38
```

I have tried to use ilastik-forge/label/ilastik133 only but this leads to other missing packages.
I guess I will have to go package per package again

**Comment by jburel** [comment]
Retested with metapackage i.e.
```
  - ilastik-meta==1.4.0b8
  - ilastik-dependencies-no-solvers==1.4.1
```

this is still not working for me

**Comment by k-dominik** [comment]
Hi @jburel,

hmmm looking at your recipe I'd have one question, what is your setting for channel priority here?

In any case I would advice against pinning any of the ilastik dependencies (that is all done in `ilastik-dependencies-no-solvers`. If you add `ilastik-dependencies-no-solvers` and `ilastik-meta` as your only packages I'd suspect it would work (if you want the beta dependencies, then indeed adding the version `1.4.1` is a good idea, but the rest I'd leave.
Or is this exactly what you have done?

I'd have to see the current meta-package you're creating to further comment.

In that case there might be some conflicts with other packages you specify.

Does the plain `conda create -n ilastik --override-channels -c ilastik-forge -c conda-forge -c defaults ilastik-dependencies-no-solvers ilastik-meta` work for you?

**Comment by jburel** [comment]
I should have indicated that I use https://github.com/jupyterhub/repo2docker  to build.
Running directly the conda commands works. The problem is elsewhere.
Closing this issue

**Comment by jburel** [comment]
For completion, I managed to get it working again using ``repo2docker`` using the master branch of repo2docker instead of the release one. The problem seems to be due to the version of conda installed by repo2docker
