### ISSUE TITLE
Broken ilastik project after upgrade to ilastik-meta 1.4.0b8 and 1.4.0b11

### ISSUE THREAD

**Issue by jburel** [ilastik/ilastik-build-conda#98]
The following pipeline https://github.com/ome/omero-guide-ilastik/blob/master/notebooks/pipelines/pixel-class-133.ilp was created using ilastik version 1.3.3 via the UI interface.
It works nicely with ``ilastik-meta 1.4.0b5`` but after upgrading to ``ilastik-meta 1.4.0b8`` it leads to 
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-71fd14454b09> in <module>
     23     )
     24 ])
---> 25 predictions = shell.workflow.batchProcessingApplet.run_export(role_data_dict, export_to_array=True)
     26 for data in predictions:
     27     # Re-organise array from tzyxc to tczyx order

/srv/conda/envs/notebook/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py in run_export(self, lane_configs, export_to_array, export_function)
    156                     lane_config,
    157                     export_function=export_function,
--> 158                     progress_callback=partial(lerpProgressSignal, global_progress_start, global_progress_end),
    159                 )
    160                 results.append(result)

/srv/conda/envs/notebook/ilastik-meta/ilastik/ilastik/applets/batchProcessing/batchProcessingApplet.py in export_dataset(self, lane_config, export_function, progress_callback)
    190         # Call customization hook
    191         self.dataExportApplet.prepare_for_entire_export()
--> 192         self.dataSelectionApplet.pushLane(lane_config)
    193         try:
    194             # Call customization hook

/srv/conda/envs/notebook/ilastik-meta/ilastik/ilastik/applets/dataSelection/dataSelectionApplet.py in pushLane(self, role_infos)
    313 
    314     def pushLane(self, role_infos: Dict[str, DatasetInfo]):
--> 315         return self.topLevelOperator.pushLane(role_infos)
    316 
    317     def dropLastLane(self):

/srv/conda/envs/notebook/ilastik-meta/ilastik/ilastik/applets/dataSelection/opDataSelection.py in pushLane(self, role_infos)
    989         except Exception as e:
    990             self.removeLane(original_num_lanes, original_num_lanes)
--> 991             raise e
    992 
    993     def dropLastLane(self):

/srv/conda/envs/notebook/ilastik-meta/ilastik/ilastik/applets/dataSelection/opDataSelection.py in pushLane(self, role_infos)
    985         try:
    986             lane = self.addLane(self.num_lanes)
--> 987             lane.configure(infos=role_infos)
    988             self.workflow.handleNewLanesAdded()
    989         except Exception as e:

/srv/conda/envs/notebook/ilastik-meta/ilastik/ilastik/applets/dataSelection/opDataSelection.py in configure(self, infos)
    870         for role_index, role_name in enumerate(self.role_names):
    871             if role_name in infos:
--> 872                 self.DatasetGroup[role_index].setValue(infos[role_name])
    873 
    874     def setupOutputs(self):

TypeError: string indices must be integers
```

ilastik is used via its API, below is the code snippet used
```
# Re-order the array tczyx -> tzyxc
input_data = input_data.swapaxes(1, 2).swapaxes(2, 3).swapaxes(3, 4)
print(input_data.shape)
# Prepare ilastik
os.environ["LAZYFLOW_THREADS"] = "2"
os.environ["LAZYFLOW_TOTAL_RAM_MB"] = "2000"
args = app.parse_args([])
args.headless = True
args.project = model_file
shell = app.main(args)

print('running ilastik using %s' % model_file)
role_data_dict = OrderedDict(
[
    (
        "Raw Data",
        [
            PreloadedArrayDatasetInfo(preloaded_array=input_data)
        ],
    )
])
predictions = shell.workflow.batchProcessingApplet.run_export(role_data_dict, export_to_array=True)

```
For reference https://github.com/ome/omero-guide-ilastik/blob/master/notebooks/idr0062_pixel_classification_zarr.ipynb

set up in conda env:
```
ilastik-dependencies-no-solvers 1.4.1                h37f11e0_5    ilastik-forge
ilastik-feature-selection 0.123.post31    py_1000_ge247095    ilastik-forge
ilastik-meta              1.4.0b8              0_gd06ea9a    ilastik-forge
ilastikrag                0.1.3.post40    py_1001_ha6e9690_g3390b38    ilastik-forge
ilastiktools              0.2.post32      np116py37_1000_h5006e0e_g970daa9    ilastik-forge

```

**Comment by jburel** [comment]
I have upgraded to ``ilastik-meta 1.4.0b11``, and upgraded/installed few dependencies.
Running the code snippet above still leads to the same error.
Any idea?
cc @k-dominik

**Comment by k-dominik** [comment]
ah right. there has been an interface change here. See maybe this test:

https://github.com/ilastik/ilastik/blob/master/tests/test_ilastik/test_applets/pixelClassification/testPixelClassificationHeadless.py#L229-L232

your code should now look something like this (please fill in the appropriate axis tags - it is highly recommended to use those).

```python
...
role_data_dict = [
        {"Raw Data": PreloadedArrayDatasetInfo(preloaded_array=input_data, axistags=...)}
]
...
```

In addition, please take not that we have now [merged](https://github.com/ilastik/ilastik/pull/2303) the first version of our Python API (which right now only supports prediction with pre-trained pixel classification projects).


Your code would roughly change to

```python
from ilastik.experimental.api import from_project_file
from xarray import DataArray

# assuming data is loaded somehow...
input_data = ...

# tag axes appropriately:
# Re-order the array tczyx -> tzyxc
input_data = DataArray(input_data, axes=("t", "c", "z", "y", "x"))

pipeline = from_project_file(project_path)
output = pipeline.predict(input_data)
```


Cheers

**Comment by jburel** [comment]
@k-dominik sorry for the slow reply
I have adjusted the code as mentioned above but I still have the same issue.
Could it be due to the fact that we are using an ilastik project created with version 1.3.3?

**Comment by k-dominik** [comment]
Hey @jburel ,

indeed, for this to work, you'd need the latest beta version (also on dockerhub)

**Comment by jburel** [comment]
Ok so older ilastik projects are not compatible. Will there be an upgrade mechanism?

**Comment by k-dominik** [comment]
what exactly do you mean by ilasik projects? The `.ilp` files are compatible

**Comment by jburel** [comment]
Sorry I meant the ``.ilp`` file. If they are compatible, the problem is coming from somewhere in that case

**Comment by k-dominik** [comment]
could you maybe past the error?

**Comment by jburel** [comment]
The error is the same as the one mentioned in the description i.e. ``TypeError: string indices must be integers``. I will re-activate my work using 1.4.0b11

**Comment by k-dominik** [comment]
hmmm. Do you remember with what version you have created the project file? And please go to 1.4.0b13 :) just to be sure

**Comment by jburel** [comment]
The project file was created using the UI version of ilastik 1.3.3
We then use the file via the API

**Comment by k-dominik** [comment]
I found the project in your repo and downloaded it... for me it worked:

```
pl = api.from_fromject_file("pixel-class-133.ilp")
data = numpy.random.randint(0, 256, (256, 256, 128, 2), dtype="uint8")
xdata = xarray.DataArray(data, dims=("x", "y", "z", "c"))
preds = pl.predict(xdata3)
```

maybe a disclaimer for this api: right now it is taking the whole volume and does not do any internal blocking.

**Comment by jburel** [comment]
ok thanks for checking. I will use b13 and we can take it from there

**Comment by jburel** [comment]
context `` ilastik-meta 1.4.0b13``and the ilastik project  ``pixel-class-133.ilp`` is used
```
role_data_dict = OrderedDict(
[
    (
        "Raw Data",
        [
            PreloadedArrayDatasetInfo(preloaded_array=input_data, axistags=vigra.AxisTags("tzyxc"))
        ],
    )
])
predictions = shell.workflow.batchProcessingApplet.run_export(role_data_dict, export_to_array=True)
```
leads to the error ``string indices must be integers``

Using the new API
```
original_data = DataArray(input_data, dims=("t", "z", "y", "x", "c"))

pipeline = from_project_file(model_file)
predictions = pipeline.predict(original_data)
```
kills the notebook kernel.
The settings
```
os.environ["LAZYFLOW_THREADS"] = "2"
os.environ["LAZYFLOW_TOTAL_RAM_MB"] = "2000"
```
that were valid when using previous versions of ilastik-meta are no longer valid or not taken into account when using the API

**Comment by k-dominik** [comment]
Hi @jburel,

okay, I guess your data is too big, to process it in one go. Our API does not allow for that yet. So for the time being, I'd suggest to modify your original code as follows:

```Python

role_data_dict = [
        {"Raw Data": PreloadedArrayDatasetInfo(preloaded_array=input_data, axistags=vigra.AxisTags("tzyxc"))},
]

predictions = shell.workflow.batchProcessingApplet.run_export(role_data_dict, export_to_array=True)
```
This should definitely work, as it uses chunk-wise processing internally.

Note that `role_data_dict` has changed it's structure to a list of dicts. So for each dataset, you'd add a separate dict here. Sorry for the inconvenience this causes.

Please let me know if this works for you.
Cheers
Dominik

**Comment by jburel** [comment]
I have made the changes but cannot test now due to another problem. This is not related to the upgrade as such. I have the problem with 1.4.0b5
This is related to vigra. Checking what I can do on the vigra front. Pasting error for info
```
Python argument types in
    vigra.vigranumpycore.constructArrayFromAxistags(type, tuple, numpy.dtype[float32], AxisTags, bool)
did not match C++ signature:
    constructArrayFromAxistags(boost::python::api::object, vigra::ArrayVector<long, std::allocator<long> >, NPY_TYPES, vigra::AxisTags, bool)
```

**Comment by k-dominik** [comment]
could you please try `vigra.defaultAxisTags("tzyxc")` in place of the `vigra.AxisTags`...

**Comment by jburel** [comment]
using ```vigra 1.11.1 py37ha1f80a5_1017   from conda-forge```

```
role_data_dict = [
    {"Raw Data":
            PreloadedArrayDatasetInfo(preloaded_array=input_data, axistags=vigra.defaultAxistags("tzyxc"))
    }
]
predictions = shell.workflow.batchProcessingApplet.run_export(role_data_dict, export_to_array=True)
```
Same error

**Comment by k-dominik** [comment]
hmmm, this is weird.. could you please check the type of input_data and make sure that this is a numpy array? (also no reordering necessary, but make sure to provide the correct axistags)

**Comment by jburel** [comment]
``input_data`` is a numpy array.
* If I do not re-order to match the order used in the ``.ilp`` file,  it again kills the kernel.
* Providing data in the order matching the order in the ``.ilp`` file, leads to the ``non matching signature`` error mentioned above
*
basically as soon as I provide data in the "correct" order we have the ``non matching signature`` error, not providing in the correct order but specifying via axis blows up the kernel due to high resource usage.

Using 1.4.0b5
(no pre-ordering, axis in this case indicate order of numpy array!)
```
role_data_dict = OrderedDict(
[
    (
        "Raw Data",
        [
            PreloadedArrayDatasetInfo(preloaded_array=input_data, axistags=vigra.defaultAxistags("tczyx"))
        ],
    )
])
``` 
leads to the ``non matching signature`` error

**Comment by k-dominik** [comment]
ah sorry, I see. I checked against the latest version... There might have been a bug in that version :/

**Comment by jburel** [comment]
I checked against both 1.4.0b5 and 1.4.0b13
it does not work. 
The report below (mentioned in my previous comment) is with 1.4.0b13
```
* If I do not re-order to match the order used in the ``.ilp`` file,  it again kills the kernel.
* Providing data in the order matching the order in the ``.ilp`` file, leads to the ``non matching signature`` error mentioned above
*
basically as soon as I provide data in the "correct" order we have the ``non matching signature`` error, not providing in the correct order but specifying via axis blows up the kernel due to high resource usage.
```
The second part of the report was with 1.4.0b5, that used to work and no longer does

**Comment by jburel** [comment]
With ``ilastik-meta 1.4.0b11 0_gd924ab6 ilastik-forge`` (output from ``conda list``)
I have the error ``string indices must be integers`` when using 
```
role_data_dict = OrderedDict(
[
    (
        "Raw Data",
        [
            PreloadedArrayDatasetInfo(preloaded_array=input_data, axistags=vigra.defaultAxistags("tzyxc"))
        ],
    )
])
```
(ordering or not ordering the numpy array (adjusting axistags accordingly) before passing it as parameter leads to the ``string indices must be integers`` error.

**Comment by jburel** [comment]
The ``string indices must be integers`` error also happens with ``ilastik-meta  1.4.0b12``

**Comment by jburel** [comment]
@k-dominik 
I have now upgraded to ``ilastik-meta              1.4.0b14             0_g632c4b7    ilastik-forge/label/ilastik140`` and I still can't get it to work
I have tried with 
``role_data_dict = [
 {"Raw Data": PreloadedArrayDatasetInfo(preloaded_array=input_data)},
]
``
``
role_data_dict = [
 {"Raw Data": PreloadedArrayDatasetInfo(preloaded_array=input_data, axistags=vigra. defaultAxistags("tzyxc"))},
]``

The error is always the same 
```
ArgumentError: Python argument types in
    vigra.vigranumpycore.constructArrayFromAxistags(type, tuple, numpy.dtype[float32], AxisTags, bool)
did not match C++ signature:
    constructArrayFromAxistags(boost::python::api::object, vigra::ArrayVector<long, std::allocator<long> >, NPY_TYPES, vigra::AxisTags, bool)
```

Using the new API is still not an option since it requires the full image to be loaded and that kill the kernel
Image used for the test: http://idr.openmicroscopy.org/webclient/?show=image-6001247
Notebook used for the test: https://github.com/ome/omero-guide-ilastik/blob/master/notebooks/idr0062_pixel_classification_zarr.ipynb. The notebook used to work nicely.

**Comment by jburel** [comment]
any idea @k-dominik?
python 3.7 is used
I had to cap h5py to work too i.e. ``h5py<3.2``. This is due to mamba when building using repo2docker

**Comment by k-dominik** [comment]
Hi @jburel , I'm looking into it. How do you create your environment (locally, for debugging purposes?).

also what type is `input_data`?

*_update_ I've tried it with an environment similar to the one you have there using our current master and the data from the notebook, and at least something like

```Python
PreloadedArrayDatasetInfo(preloaded_array=input_data, axistags=vigra. defaultAxistags("tzyxc"))

``` 
works without error for me


I noticed, that you pin some dependencies to the ilastik133 tag. I would advice against that, especially when using it with any ilastik 1.4.0x version

**Comment by jburel** [comment]
I use ``repo2docker`` to create the env since I am running the notebook on binderhub afterwards. Note that as indicated previously you will need to cap h5py i.e. ``h5py<3.2`` b/c of mamba
``input_data`` is a 5D numpy array.

**Comment by jburel** [comment]
On my working branch, I am not pinning anything excepting ``h5py`` and using the latest version available on conda i.e.
``ilastik-forge/label/ilastik140::ilastik-meta``
and I still cannot get it to work due to the ``vigra`` error.

How did you create your environment?

**Comment by k-dominik** [comment]
I've used our `devenv.py` script in `ilastik/scripts`... But I didn't try forcing anything on ilastik140 or anything. Channels `ilastik-forge`, `conda-forge`, `ome`...


```bash
# assuming current ilastik meta was cloned from source, submodules initialized and set to master
# in ilastik-meta folder
ilastik/scripts/devenv.py create -n omero-devenv -c ilastik-forge conda-forge ome -p ilastik-dependencies-no-solvers jupyter notebook ipdb black pre-commit omero-py
```
then after activating this I installed `ome-zarr` via pip

**Comment by k-dominik** [comment]
could you send me a link to the branch you are currently using?

**Comment by jburel** [comment]
ok thanks
The problem could come from what repo2docker is using to generate the env.

**Comment by k-dominik** [comment]
do you have a link to some kind of ci/build log for that?

**Comment by k-dominik** [comment]
in any case, if it is using the environment yaml from the [binder folder](https://github.com/ome/omero-guide-ilastik/blob/master/binder/environment.yml) then I'd suggest removing _all_ version specifiers / channel labels (except for the ones you absolutely need, my). Also I'd make sure to use strict channel priority. I cannot see that `mamba` is a dependency.

**Comment by jburel** [comment]
mamba is a package manager used under the hood
I followed that approach in the past i.e. using ``ilastik-dependencies-no-solvers`` and ``ilastik-meta`` see https://github.com/ome/omero-guide-ilastik/pull/7/
but changes under the hood were breaking the notebooks at regular intervals and this is not something we can afford prior to training sessions.
so I opted to pin the version e.g. https://github.com/ome/omero-guide-ilastik/pull/15

**Comment by jburel** [comment]
Thanks @k-dominik for looking into it 
Some progress this time, the pixels classification works with the following env

```
ilastik-dependencies-no-solvers 1.4.3                h37f11e0_0    ilastik-forge
ilastik-feature-selection 0.123.post31    py_1000_ge247095    ilastik-forge
ilastik-meta              1.4.0b14             0_g632c4b7    ilastik-forge/label/ilastik140
ilastikrag                0.1.3.post40    py_1001_ha6e9690_g3390b38    ilastik-forge
ilastiktools              0.2.post32      np116py37_1000_h5006e0e_g970daa9    ilastik-forge
```
I only have a problem to solve with itkwidgets but that it is independent of ilastik
Closing this issue since the problem ``string indices must be integers`` is no longer there

Do you have an idea when the new API will be able to handle "chunks"?
